// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/javiclavero/go-auth-service/ent/schema"
	"github.com/javiclavero/go-auth-service/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUseType is the schema descriptor for use_type field.
	userDescUseType := userFields[1].Descriptor()
	// user.DefaultUseType holds the default value on creation for the use_type field.
	user.DefaultUseType = userDescUseType.Default.(int64)
	// userDescUseUsername is the schema descriptor for use_username field.
	userDescUseUsername := userFields[2].Descriptor()
	// user.UseUsernameValidator is a validator for the "use_username" field. It is called by the builders before save.
	user.UseUsernameValidator = userDescUseUsername.Validators[0].(func(string) error)
	// userDescUsePwd is the schema descriptor for use_pwd field.
	userDescUsePwd := userFields[3].Descriptor()
	// user.UsePwdValidator is a validator for the "use_pwd" field. It is called by the builders before save.
	user.UsePwdValidator = userDescUsePwd.Validators[0].(func(string) error)
	// userDescUseEmail is the schema descriptor for use_email field.
	userDescUseEmail := userFields[4].Descriptor()
	// user.UseEmailValidator is a validator for the "use_email" field. It is called by the builders before save.
	user.UseEmailValidator = userDescUseEmail.Validators[0].(func(string) error)
	// userDescUseResetToken is the schema descriptor for use_reset_token field.
	userDescUseResetToken := userFields[5].Descriptor()
	// user.UseResetTokenValidator is a validator for the "use_reset_token" field. It is called by the builders before save.
	user.UseResetTokenValidator = userDescUseResetToken.Validators[0].(func(string) error)
	// userDescUseAccessToken is the schema descriptor for use_access_token field.
	userDescUseAccessToken := userFields[7].Descriptor()
	// user.UseAccessTokenValidator is a validator for the "use_access_token" field. It is called by the builders before save.
	user.UseAccessTokenValidator = userDescUseAccessToken.Validators[0].(func(string) error)
	// userDescUseCreatedAt is the schema descriptor for use_created_at field.
	userDescUseCreatedAt := userFields[9].Descriptor()
	// user.DefaultUseCreatedAt holds the default value on creation for the use_created_at field.
	user.DefaultUseCreatedAt = userDescUseCreatedAt.Default.(func() time.Time)
	// userDescUseUpdatedAt is the schema descriptor for use_updated_at field.
	userDescUseUpdatedAt := userFields[10].Descriptor()
	// user.DefaultUseUpdatedAt holds the default value on creation for the use_updated_at field.
	user.DefaultUseUpdatedAt = userDescUseUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUseUpdatedAt holds the default value on update for the use_updated_at field.
	user.UpdateDefaultUseUpdatedAt = userDescUseUpdatedAt.UpdateDefault.(func() time.Time)
}
